services:
    api:
        build: ./api
        ports:
            - "8000:8000"
        volumes:
            - ./api:/api
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        command: bash -c "python manage.py runserver 0.0.0.0:8000"

    web:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/public:/frontend/public
            - ./frontend/src:/frontend/src
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
