services:

    server:
        build: ./server
        ports:
            - "443:443"
        volumes:
            - ./server:/server
            - /server/node_modules
        environment:
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    client:
        build: ./client
        ports:
            - "80:80"
        volumes:
            - ./frontend/public:/frontend/public
            - ./frontend/src:/frontend/src
