services:
    api:
        build: ./api
        ports:
            - "8000:8000"
        volumes:
            - ./api:/api
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        environment:
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    web:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/public:/frontend/public
            - ./frontend/src:/frontend/src
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"

    auth:
        build: ./auth-server
        ports:
            - "3080:3080"
        volumes:
            - ./auth-server:/auth-server
            - /auth-server/node_modules