db.faculty.drop();
db.faculty.insertOne(
    {
        "email":"bhngyen3@crimson.ua.edu",
        "availability":{
            "Monday":[true,false,true,false,true,false,true,false,true,false,true,false],
            "Tuesday":[true,false,true,false,true,false,true,false,true,false,true,false],
            "Wednesday":[true,false,true,false,true,false,true,false,true,false,true,false],
            "Thursday":[true,false,true,false,true,false,true,false,true,false,true,false],
            "Friday":[true,false,true,false,true,false,true,false,true,false,true,false]},
        "facultyFirst":"Brandon",
        "facultyLast":"Nguyen"
    }
)

db.requests.drop();
db.requests.insertOne(
    {
        "date":"05/10/2024",
        "facultyFirst":"Monica",
        "facultyLast":"Anderson",
        "status":"Accepted",
        "studentFirst":"David",
        "studentLast":"Dillard",
        "time":"14:00"
    }
)